-- =====================================================================
-- PetroFlow - Script de Configuración de Base de Datos para Supabase
-- =====================================================================
-- Este script crea todas las tablas, llaves primarias/foráneas, triggers y
-- restricciones necesarias en Supabase para el funcionamiento del CRUD.
-- Copia este código y ejecútalo en la consola de Supabase (SQL Editor).

-- 1. Habilitar la extensión UUID (por si acaso no está activa)
create extension if not exists "uuid-ossp";

-- 2. Eliminar tablas previas si existen (en orden inverso de dependencia)
drop table if exists public.fluid_reports cascade;
drop table if exists public.pozos cascade;
drop table if exists public.campos cascade;
drop table if exists public.profiles cascade;

-- 3. Crear tabla profiles (Perfiles vinculados al Auth de Supabase)
create table public.profiles (
    id uuid references auth.users on delete cascade primary key,
    full_name text not null,
    role text not null check (role in ('ADMIN', 'SUPERVISOR', 'INGENIERO_CAMPO')),
    is_active boolean default true not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Crear tabla campos (Campos petroleros)
create table public.campos (
    id uuid default gen_random_uuid() primary key,
    name text not null unique,
    region text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Crear tabla pozos (Pozos petroleros vinculados a un Campo)
create table public.pozos (
    id uuid default gen_random_uuid() primary key,
    name text not null unique,
    campo_id uuid references public.campos(id) on delete cascade not null,
    status text not null check (status in ('PERFORACION', 'PRODUCCION', 'CERRADO', 'MANTENIMIENTO')),
    depth_target_ft double precision not null check (depth_target_ft > 0),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Crear tabla fluid_reports (Reportes diarios de fluidos)
create table public.fluid_reports (
    id bigint generated by default as identity primary key,
    pozo_id uuid references public.pozos(id) on delete cascade not null,
    ingeniero_id uuid references public.profiles(id) on delete restrict not null,
    date date not null,
    mud_density double precision not null check (mud_density >= 0),
    viscosity integer not null check (viscosity >= 0),
    pressure double precision not null check (pressure >= 0),
    ph double precision not null check (ph >= 0 and ph <= 14),
    notes text not null default '',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Trigger para copiar automáticamente datos de registro de auth.users a public.profiles
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role, is_active)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Nuevo Ingeniero'),
    coalesce(new.raw_user_meta_data->>'role', 'INGENIERO_CAMPO'),
    true
  );
  return new;
end;
$$ language plpgsql security definer;

-- Asociar el trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 8. Poblar la tabla de Campos Petroleros con algunos datos iniciales semilla
insert into public.campos (name, region)
values 
('Campo Cantarell', 'Región Marina Noreste'),
('Campo Ku-Maloob-Zaap', 'Región Marina Noreste'),
('Campo Quesqui', 'Región Terrestre Sur'),
('Campo Ixachi', 'Región Terrestre Veracruz'),
('Campo Ayatsil', 'Región Marina Suroeste')
on conflict (name) do nothing;

-- 9. Deshabilitar RLS temporalmente para simplificar pruebas escolares con anon-key
-- Nota: En producción deben crearse políticas de acceso selectivas.
alter table public.profiles disable row level security;
alter table public.campos disable row level security;
alter table public.pozos disable row level security;
alter table public.fluid_reports disable row level security;

-- 10. Otorgar permisos básicos a roles anónimos y autenticados
grant all on table public.profiles to anon, authenticated, service_role;
grant all on table public.campos to anon, authenticated, service_role;
grant all on table public.pozos to anon, authenticated, service_role;
grant all on table public.fluid_reports to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
